const puppeteer = require("puppeteer");

(async () => {
	const browser = await puppeteer.launch({ headless: "new" });
	const page = await browser.newPage();

	// GitHub Actions may run on localhost:4173 by default for vite preview
	await page.setViewport({ width: 1280, height: 880 });

	// Set localStorage for the target origin before any of its scripts run
	await page.evaluateOnNewDocument(() => {
		localStorage.setItem(
			"grid-storage",
			JSON.stringify({
				state: {
					grid: {
						cells: [
							[
								{
									active: true,
									adjacency: "none",
									adjacency_bonus: 0,
									bonus: 0,
									image: "apollo.webp",
									label: "Apollo Figurine",
									module: "AP",
									sc_eligible: false,
									supercharged: false,
									tech: "bobble",
									total: 0,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "none",
									adjacency_bonus: 0,
									bonus: 0,
									image: "null.webp",
									label: "-null- Figurine",
									module: "NB",
									sc_eligible: false,
									supercharged: false,
									tech: "bobble",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.17,
									bonus: 0.29,
									image: "shield-upgrade.webp",
									label: "Shield Upgrade Tau",
									module: "Xb",
									sc_eligible: true,
									supercharged: false,
									tech: "shield",
									total: 0.3393,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.22000000000000003,
									bonus: 0.3,
									image: "shield-upgrade.webp",
									label: "Shield Upgrade Theta",
									module: "Xa",
									sc_eligible: true,
									supercharged: false,
									tech: "shield",
									total: 0.366,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "lesser",
									adjacency_bonus: 0.0001,
									bonus: 0.01,
									image: "shield.webp",
									label: "Defensive Shields",
									module: "DS",
									sc_eligible: true,
									supercharged: false,
									tech: "shield",
									total: 0.0101,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.135,
									bonus: 0.38,
									image: "phase-upgrade.webp",
									label: "Phase Beam Upgrade Sigma",
									module: "Xc",
									sc_eligible: true,
									supercharged: false,
									tech: "phase",
									total: 0.4313,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "lesser",
									adjacency_bonus: 0.04020000000000001,
									bonus: 1,
									image: "phase-beam.webp",
									label: "Phase Beam",
									module: "PB",
									sc_eligible: true,
									supercharged: false,
									tech: "phase",
									total: 1.0402,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "lesser",
									adjacency_bonus: 0.05,
									bonus: 0.07,
									image: "fourier.webp",
									label: "Fourier De-Limiter",
									module: "FD",
									sc_eligible: true,
									supercharged: false,
									tech: "phase",
									total: 0.07350000000000001,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.15500000000000003,
									bonus: 0.38,
									image: "infra-upgrade.webp",
									label: "Infraknife Accelerator Upgrade Sigma",
									module: "Xc",
									sc_eligible: true,
									supercharged: false,
									tech: "infra",
									total: 0.4389,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.17,
									bonus: 0.39,
									image: "infra-upgrade.webp",
									label: "Infraknife Accelerator Upgrade Tau",
									module: "Xb",
									sc_eligible: true,
									supercharged: false,
									tech: "infra",
									total: 0.45630000000000004,
									type: "bonus",
									value: 0,
								},
							],
							[
								{
									active: true,
									adjacency: "none",
									adjacency_bonus: 0,
									bonus: 0,
									image: "atlas.webp",
									label: "Atlas Figurine",
									module: "AT",
									sc_eligible: false,
									supercharged: false,
									tech: "bobble",
									total: 0,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "none",
									adjacency_bonus: 0,
									bonus: 0,
									image: "teleport.webp",
									label: "Teleport Receiver",
									module: "TP",
									sc_eligible: false,
									supercharged: false,
									tech: "teleporter",
									total: 0,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.17,
									bonus: 0.07,
									image: "ablative.webp",
									label: "Ablative Armor",
									module: "AA",
									sc_eligible: true,
									supercharged: false,
									tech: "shield",
									total: 0.08190000000000001,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.17,
									bonus: 0.28,
									image: "shield-upgrade.webp",
									label: "Shield Upgrade Sigma",
									module: "Xc",
									sc_eligible: true,
									supercharged: false,
									tech: "shield",
									total: 0.32760000000000006,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.07,
									bonus: 0,
									image: "emeril-trail.webp",
									label: "Emeril Starship Trail",
									module: "ET",
									sc_eligible: false,
									supercharged: false,
									tech: "trails",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.17,
									bonus: 0.4,
									image: "phase-upgrade.webp",
									label: "Phase Beam Upgrade Theta",
									module: "Xa",
									sc_eligible: true,
									supercharged: false,
									tech: "phase",
									total: 0.468,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.135,
									bonus: 0.39,
									image: "phase-upgrade.webp",
									label: "Phase Beam Upgrade Tau",
									module: "Xb",
									sc_eligible: true,
									supercharged: false,
									tech: "phase",
									total: 0.44265,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.07,
									bonus: 0.03,
									image: "q-resonator.webp",
									label: "Q-Resonator",
									module: "QR",
									sc_eligible: true,
									supercharged: false,
									tech: "infra",
									total: 0.0321,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.255,
									bonus: 1,
									image: "infra.webp",
									label: "Infraknife Accelerator",
									module: "IK",
									sc_eligible: true,
									supercharged: true,
									tech: "infra",
									total: 1.5687499999999999,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.15500000000000003,
									bonus: 0.4,
									image: "infra-upgrade.webp",
									label: "Infraknife Accelerator Upgrade Theta",
									module: "Xa",
									sc_eligible: true,
									supercharged: true,
									tech: "infra",
									total: 0.5775,
									type: "bonus",
									value: 0,
								},
							],
							[
								{
									active: true,
									adjacency: "lesser",
									adjacency_bonus: 0.09,
									bonus: 0,
									image: "cadmium.webp",
									label: "Cadmium Drive",
									module: "CD",
									sc_eligible: false,
									supercharged: false,
									tech: "hyper",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "lesser",
									adjacency_bonus: 0.0801,
									bonus: 0,
									image: "indium.webp",
									label: "Indium Drive",
									module: "ID",
									sc_eligible: false,
									supercharged: false,
									tech: "hyper",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "lesser",
									adjacency_bonus: 0.040100000000000004,
									bonus: 0,
									image: "emeril.webp",
									label: "Emeril Drive",
									module: "ED",
									sc_eligible: false,
									supercharged: false,
									tech: "hyper",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.15500000000000003,
									bonus: 0,
									image: "stealth-trail.webp",
									label: "Stealth Starship Trail",
									module: "ST",
									sc_eligible: false,
									supercharged: false,
									tech: "trails",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.325,
									bonus: 0.06,
									image: "polo.webp",
									label: "Polo Figurine",
									module: "PB",
									sc_eligible: true,
									supercharged: false,
									tech: "trails",
									total: 0.385,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.15500000000000003,
									bonus: 0,
									image: "cadmium-trail.webp",
									label: "Cadmium Starship Trail",
									module: "CT",
									sc_eligible: false,
									supercharged: false,
									tech: "trails",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.17,
									bonus: 0,
									image: "instability.webp",
									label: "Instability Drive",
									module: "ID",
									sc_eligible: false,
									supercharged: false,
									tech: "pulse",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.255,
									bonus: 0.5,
									image: "pulse-upgrade.webp",
									label: "Pulse Engine Upgrade Theta",
									module: "Xa",
									sc_eligible: true,
									supercharged: true,
									tech: "pulse",
									total: 0.7843749999999999,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.255,
									bonus: 0.49,
									image: "pulse-upgrade.webp",
									label: "Pulse Engine Upgrade Tau",
									module: "Xb",
									sc_eligible: true,
									supercharged: true,
									tech: "pulse",
									total: 0.7686875,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.135,
									bonus: 0,
									image: "sublight.webp",
									label: "Sub-Light Amplifier",
									module: "SL",
									sc_eligible: false,
									supercharged: false,
									tech: "pulse",
									total: 0,
									type: "bonus",
									value: 0,
								},
							],
							[
								{
									active: true,
									adjacency: "lesser",
									adjacency_bonus: 0.0801,
									bonus: 0.01,
									image: "hyperdrive.webp",
									label: "Hyperdrive",
									module: "HD",
									sc_eligible: true,
									supercharged: false,
									tech: "hyper",
									total: 0.0901,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.26,
									bonus: 0.32,
									image: "hyper-upgrade.webp",
									label: "Hyperdrive Upgrade Theta",
									module: "Xa",
									sc_eligible: true,
									supercharged: false,
									tech: "hyper",
									total: 0.4032,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.21000000000000002,
									bonus: 0.3,
									image: "hyper-upgrade.webp",
									label: "Hyperdrive Upgrade Sigma",
									module: "Xc",
									sc_eligible: true,
									supercharged: false,
									tech: "hyper",
									total: 0.363,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.24000000000000005,
									bonus: 0,
									image: "golden-trail.webp",
									label: "Golden Starship Trail",
									module: "GT",
									sc_eligible: false,
									supercharged: false,
									tech: "trails",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.325,
									bonus: 0.05,
									image: "artemis.webp",
									label: "Artemis Figurine",
									module: "AB",
									sc_eligible: true,
									supercharged: false,
									tech: "trails",
									total: 0.375,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.24000000000000005,
									bonus: 0,
									image: "chromatic-trail.webp",
									label: "Chromatic Starship Trail",
									module: "RT",
									sc_eligible: false,
									supercharged: false,
									tech: "trails",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.17,
									bonus: 0.11,
									image: "flight-assist.webp",
									label: "Flight Assist Override",
									module: "FA",
									sc_eligible: true,
									supercharged: false,
									tech: "pulse",
									total: 0.1287,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.255,
									bonus: 0.48,
									image: "pulse-upgrade.webp",
									label: "Pulse Engine Upgrade Sigma",
									module: "Xc",
									sc_eligible: true,
									supercharged: false,
									tech: "pulse",
									total: 0.6023999999999999,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.22000000000000003,
									bonus: 0.26,
									image: "photonix.webp",
									label: "Photonix Core",
									module: "PC",
									sc_eligible: true,
									supercharged: false,
									tech: "pulse",
									total: 0.31720000000000004,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "lesser",
									adjacency_bonus: 0.0002,
									bonus: 0.01,
									image: "pulse.webp",
									label: "Pulse Engine",
									module: "PE",
									sc_eligible: true,
									supercharged: false,
									tech: "pulse",
									total: 0.0102,
									type: "core",
									value: 0,
								},
							],
							[
								{
									active: true,
									adjacency: "lesser",
									adjacency_bonus: 0.050100000000000006,
									bonus: 0,
									image: "atlantid.webp",
									label: "Atlantid Drive",
									module: "AD",
									sc_eligible: false,
									supercharged: false,
									tech: "hyper",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.21000000000000002,
									bonus: 0.31,
									image: "hyper-upgrade.webp",
									label: "Hyperdrive Upgrade Tau",
									module: "Xb",
									sc_eligible: true,
									supercharged: false,
									tech: "hyper",
									total: 0.3751,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.17,
									bonus: 0,
									image: "emergency.webp",
									label: "Emergency Warp Unit",
									module: "EW",
									sc_eligible: true,
									supercharged: false,
									tech: "hyper",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.17,
									bonus: 0,
									image: "sputtering-trail.webp",
									label: "Sputtering Starship Trail",
									module: "SP",
									sc_eligible: false,
									supercharged: false,
									tech: "trails",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.24000000000000002,
									bonus: 0.05,
									image: "squid.webp",
									label: "Tentacled Figurine",
									module: "SB",
									sc_eligible: true,
									supercharged: false,
									tech: "trails",
									total: 0.062000000000000006,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.17,
									bonus: 0,
									image: "temporal-trail.webp",
									label: "Temporal Starship Trail",
									module: "TT",
									sc_eligible: false,
									supercharged: false,
									tech: "trails",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "lesser",
									adjacency_bonus: 0.0002,
									bonus: 0.01,
									image: "launch.webp",
									label: "Launch Thruster",
									module: "LT",
									sc_eligible: false,
									supercharged: false,
									tech: "launch",
									total: 0.0102,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.22000000000000003,
									bonus: 0.29,
									image: "launch-upgrade.webp",
									label: "Launch Thruster Upgrade Tau",
									module: "Xb",
									sc_eligible: true,
									supercharged: false,
									tech: "launch",
									total: 0.3538,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.17,
									bonus: 0.28,
									image: "launch-upgrade.webp",
									label: "Launch Thruster Upgrade Sigma",
									module: "Xc",
									sc_eligible: true,
									supercharged: false,
									tech: "launch",
									total: 0.32760000000000006,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.07,
									bonus: 0.056,
									image: "tubes.webp",
									label: "Large Rocket Tubes",
									module: "LR",
									sc_eligible: true,
									supercharged: false,
									tech: "rocket",
									total: 0.05992,
									type: "bonus",
									value: 0,
								},
							],
							[
								{
									active: true,
									adjacency: "none",
									adjacency_bonus: 0,
									bonus: 0,
									image: "nada.webp",
									label: "Nada Figurine",
									module: "NA",
									sc_eligible: false,
									supercharged: false,
									tech: "bobble",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "none",
									adjacency_bonus: 0,
									bonus: 0,
									image: "economy.webp",
									label: "Economy Scanner",
									module: "ES",
									sc_eligible: false,
									supercharged: false,
									tech: "scanners",
									total: 0,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "none",
									adjacency_bonus: 0,
									bonus: 0,
									image: "conflict.webp",
									label: "Conflict Scanner",
									module: "CS",
									sc_eligible: false,
									supercharged: false,
									tech: "scanners",
									total: 0,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "none",
									adjacency_bonus: 0,
									bonus: 0,
									image: "cargo.webp",
									label: "Cargo Scan Deflector",
									module: "CD",
									sc_eligible: false,
									supercharged: false,
									tech: "scanners",
									total: 0,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: "none",
									adjacency_bonus: 0,
									bonus: 0,
									image: "aquajets.webp",
									label: "Aqua-Jets",
									module: "AJ",
									module_position: [4, 5],
									sc_eligible: false,
									supercharged: false,
									tech: "aqua",
									total: 0,
									type: "core",
									value: 0,
								},
								{
									active: true,
									adjacency: false,
									adjacency_bonus: 0,
									bonus: 0,
									image: null,
									label: "",
									module: null,
									sc_eligible: false,
									supercharged: false,
									tech: null,
									total: 0,
									type: "",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.135,
									bonus: 0,
									image: "recharger.webp",
									label: "Launch Auto-Charger",
									module: "RC",
									sc_eligible: false,
									supercharged: false,
									tech: "launch",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.255,
									bonus: 0.3,
									image: "launch-upgrade.webp",
									label: "Launch Thruster Upgrade Theta",
									module: "Xa",
									sc_eligible: true,
									supercharged: false,
									tech: "launch",
									total: 0.3765,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.17,
									bonus: 0,
									image: "efficient.webp",
									label: "Efficient Thrusters",
									module: "EF",
									sc_eligible: false,
									supercharged: false,
									tech: "launch",
									total: 0,
									type: "bonus",
									value: 0,
								},
								{
									active: true,
									adjacency: "greater",
									adjacency_bonus: 0.085,
									bonus: 1,
									image: "rocket.webp",
									label: "Rocket Launger",
									module: "RL",
									sc_eligible: true,
									supercharged: false,
									tech: "rocket",
									total: 1.085,
									type: "core",
									value: 0,
								},
							],
						],
						height: 6,
						width: 10,
					},
					isSharedGrid: false,
				},
				version: 0,
			})
		);
	});

	await page.goto("http://localhost:5173", { waitUntil: "networkidle0" });
	await page.screenshot({ path: "public/assets/img/screenshots/screenshot.png", fullPage: true });
	await page.screenshot({
		path: "public/assets/img/screenshots/screenshot_desktop.png",
		fullPage: true,
	});

	await page.setViewport({ width: 375, height: 667 });
	await page.goto("http://localhost:5173", { waitUntil: "networkidle0" });
	await page.screenshot({
		path: "public/assets/img/screenshots/screenshot_mobile.png",
		fullPage: false,
	});

	await page.setViewport({ width: 800, height: 1280 });
	await page.goto("http://localhost:5173", { waitUntil: "networkidle0" });
	await page.screenshot({
		path: "public/assets/img/screenshots/screenshot_tablet.png",
		fullPage: false,
	});

	await browser.close();
})();
